"""Render Markdown LaTeX formulas to local theme-aware SVG assets."""

from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs" / "MATHEMATICS_SOURCE.md"
OUTPUT = ROOT / "docs" / "MATHEMATICS.md"
ASSETS = ROOT / "docs" / "assets" / "math"
FORMULA = re.compile(
    r"\$\$(.*?)\$\$|(?<!\$)\$(?!\$)([^\n$]+?)(?<!\$)\$(?!\$)",
    re.DOTALL,
)


@dataclass(frozen=True)
class Formula:
    display: bool
    tex: str


def _formulas(source: str) -> list[Formula]:
    return [
        Formula(match.group(1) is not None, (match.group(1) or match.group(2)).strip())
        for match in FORMULA.finditer(source)
    ]


def _latex_document(formulas: list[Formula]) -> str:
    lines = [
        r"\documentclass{article}",
        r"\usepackage{amsmath,amssymb}",
        r"\pagestyle{empty}",
        r"\begin{document}",
    ]
    for formula in formulas:
        body = rf"\displaystyle {formula.tex}" if formula.display else formula.tex
        lines.extend((r"\thispagestyle{empty}", rf"\noindent\({body}\)", r"\newpage"))
    lines.append(r"\end{document}")
    return "\n".join(lines) + "\n"


def _run(command: list[str], directory: Path) -> None:
    completed = subprocess.run(
        command,
        cwd=directory,
        text=True,
        capture_output=True,
        check=False,
    )
    if completed.returncode:
        raise RuntimeError(completed.stdout + completed.stderr)


def _render(formulas: list[Formula]) -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)
    for asset in ASSETS.glob("equation-*.svg"):
        asset.unlink()

    with tempfile.TemporaryDirectory(prefix="wishart-math-") as temporary:
        directory = Path(temporary)
        tex = directory / "equations.tex"
        tex.write_text(_latex_document(formulas), encoding="utf-8")
        _run(
            [
                shutil.which("latex") or "latex",
                "-disable-installer",
                "-interaction=nonstopmode",
                "-halt-on-error",
                f"-output-directory={directory}",
                str(tex),
            ],
            directory,
        )
        _run(
            [
                shutil.which("dvisvgm") or "dvisvgm",
                "--page=1-",
                "--bbox=min",
                "--no-fonts",
                "--currentcolor=#000",
                f"--output={ASSETS / 'equation-%3p.svg'}",
                str(directory / "equations.dvi"),
            ],
            directory,
        )


def _theme_svg(path: Path) -> None:
    source = path.read_text(encoding="utf-8")
    start = source.index("<svg")
    close = source.index(">", start) + 1
    style = (
        "<style>:root{color:#24292f}"
        "@media(prefers-color-scheme:dark){:root{color:#e6edf3}}</style>"
    )
    path.write_text(source[:close] + style + source[close:], encoding="utf-8")


def _markdown(source: str) -> str:
    index = 0

    def replace(match: re.Match[str]) -> str:
        nonlocal index
        index += 1
        label = "Equation" if match.group(1) is not None else "Formula"
        return f"![{label} {index:03d}](assets/math/equation-{index:03d}.svg)"

    header = (
        "<!-- Generated by scripts/render_mathematics.py from "
        "docs/MATHEMATICS_SOURCE.md. -->\n"
    )
    return header + FORMULA.sub(replace, source)


def main() -> None:
    source = SOURCE.read_text(encoding="utf-8")
    formulas = _formulas(source)
    _render(formulas)
    assets = sorted(ASSETS.glob("equation-*.svg"))
    if len(assets) != len(formulas):
        raise RuntimeError(f"rendered {len(assets)} SVGs for {len(formulas)} formulas")
    for asset in assets:
        _theme_svg(asset)
    OUTPUT.write_text(_markdown(source), encoding="utf-8")


if __name__ == "__main__":
    main()
